/*
    Consider the following algorithm
    Start with a positive number n
    If n is even, then divide by 2
    If n is odd, then multiply by 3 and add 1
    Repeat above two steps until n becomes 1
    The sequence generated by above algorithm is called Ascol sequence.
    For example, if the Ascol sequence of the number 7 is computed as
    7, 22, 11. 34, 17, 52, 26, 13, 40, 20, 10,5 16, 8,4,2,1
    Write a C program with function named isAscolSequence () that takes an array as argument tests whether the contains Ascol sequence or not
*/

#include "stdio.h"
#define s 7
void isAscolSequence(int[]);

int main() {
    int i, sequence[s];
    printf("\nEnter your sequence\n");
    for (i=0; i < s; i++) scanf("%d", &sequence[i]);
    isAscolSequence(sequence);
    return 0;
}

void isAscolSequence(int sequence[]) {
    int i = 0, a = sequence[i], tn;
    char cond = 't';
    while (i < (s-1) && sequence[i] != 1) {
        if (sequence[i] % 2) tn = sequence[i] * 3 + 1;
        else tn = sequence[i] / 2;
        if (sequence[i+1] != tn) {
            cond = 'f';
            break;
        }
        i++;
    }

    if (cond == 't') printf("\nEntered Sequence is ASCOL Sequence");
    else printf("\nEntered Sequence is Not ASCOL Sequence");
}